/*
 * This source file was generated by the Gradle 'init' task
 */
package la.nisa

import kotlinx.io.bytestring.ByteString
import kotlinx.io.bytestring.encodeToByteString
import org.multipaz.cbor.Cbor
import org.multipaz.cbor.buildCborMap
import org.multipaz.mdoc.connectionmethod.MdocConnectionMethod
import org.multipaz.mdoc.connectionmethod.MdocConnectionMethodBle
import org.multipaz.mdoc.connectionmethod.MdocConnectionMethodNfc
import org.multipaz.mdoc.role.MdocRole
import org.multipaz.nfc.HandoverRequestRecord
import org.multipaz.nfc.NdefMessage
import org.multipaz.nfc.NdefRecord
import org.multipaz.util.UUID

fun main() {
    App.generateBleHandover()
}

class App {
    companion object {
        val hexFormat = HexFormat {
            upperCase = true
            bytes {
                bytePrefix = "0x"
                byteSeparator = ", "
            }
        }
        val uuid = UUID.fromString("82186040-093c-4ff9-a90b-6994d231b2a4")

        fun generateBleHandover() {
            val bleMethod = MdocConnectionMethodBle(false, true, null, uuid)
            val message = generateHandoverRequestMessage(listOf(bleMethod));
            println(message.encode().toHexString(hexFormat))
            println(message.encode().size)
        }

        fun generateNfcHandover() {
            val nfcMethod = MdocConnectionMethodNfc(200, 200);
            val message = generateHandoverRequestMessage(listOf(nfcMethod))
            println(message.encode().toHexString(hexFormat))
            println(message.encode().size)
        }
    }
}

// copied from mdocReaderNfcHandoff.kt
fun generateHandoverRequestMessage(
    methods: List<MdocConnectionMethod>,
): NdefMessage {
    val auxiliaryReferences = listOf<String>()
    val carrierConfigurationRecords = mutableListOf<NdefRecord>()
    val alternativeCarrierRecords = mutableListOf<NdefRecord>()
    for (method in methods) {
        val ndefRecordAndAlternativeCarrier = method.toNdefRecord(
            auxiliaryReferences = auxiliaryReferences,
            role = MdocRole.MDOC_READER,
            skipUuids = false
        )
        if (ndefRecordAndAlternativeCarrier != null) {
            carrierConfigurationRecords.add(ndefRecordAndAlternativeCarrier.first)
            alternativeCarrierRecords.add(ndefRecordAndAlternativeCarrier.second)
        }
    }
    val handoverRequestRecord = HandoverRequestRecord(
        version = 0x15,
        embeddedMessage = NdefMessage(alternativeCarrierRecords)
    )
    // TODO: make it possible for caller to specify readerEngagement
    val encodedReaderEngagement = Cbor.encode(
        buildCborMap {
            put(0L, "1.0")
        }
    )
    return NdefMessage(
        listOf(
            handoverRequestRecord.generateNdefRecord(),
            NdefRecord(
                tnf = NdefRecord.Tnf.EXTERNAL_TYPE,
                type = "iso.org:18013:readerengagement".encodeToByteString(),
                id = "mdocreader".encodeToByteString(),
                payload = ByteString(encodedReaderEngagement)
            )
        ) + carrierConfigurationRecords
    )
}
